

package view;

import controller.Direccion;
import controller.Persona;
import controller.Planta;
import java.util.Random;
import javax.swing.table.DefaultTableModel;
import java.awt.Color;
import javax.swing.JOptionPane;
import model.Gestion;
/**
 *
 * @author Matias Borquez
 */
public class Sistema extends javax.swing.JFrame {

   private Gestion gestionPersona;
   DefaultTableModel modelo;
   //variable de tabla
   private DefaultTableModel dtm;
   private Object[] o = new Object[10];
   //variable para ejes del mouse
   int xMouse, yMouse;
    
    public Sistema() {
        initComponents();
        
        
        //inicializa gestionPersona
        this.gestionPersona = new Gestion();
        //posicion del jframe
        setLocationRelativeTo(bg);
        //definir la tabla 
        dtm = (DefaultTableModel) tblPersona.getModel();
        tblPersona.setModel(modelo);
        
        
        //abrir jtable
        Tabla tabla2 = new Tabla();
        tabla2.setVisible(true);
    }
    
    
    public void nuevaTabla(){
        //Al pasarl os datos de la tabla, limpiamos la primera tabla 
        dtm = new DefaultTableModel();
        tblPersona.setModel(modelo);
        
    }
    
    Random random = new Random();
    public double  nSeguimiento(){
        int numero = random.nextInt(1000); //generar un numero aleatorio entre 0 y 9999
        return numero; 
    }
    
    
 
 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        lbl = new javax.swing.JLabel();
        lblDatos = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        exitBtn = new javax.swing.JPanel();
        txtX = new javax.swing.JLabel();
        txtRut = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txtNombre = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        txtApellido = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        lblDireccion = new javax.swing.JLabel();
        lblCalle = new javax.swing.JLabel();
        txtCalle = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        txtComuna = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        btnGuardar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtPlanta = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        scrPersona = new javax.swing.JScrollPane();
        tblPersona = new javax.swing.JTable();
        btnListar = new javax.swing.JButton();
        btnMostrar = new javax.swing.JButton();
        btnAñadir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setPreferredSize(new java.awt.Dimension(900, 420));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Download premium image of Tropical no Text vegetation outdoors_ by Sataphorn Srijantra about tropical leaf iphone wallpaper, safari jungle animals graphic, banana leaf 3d rendering, wallpaper green, and 3 dimensional 13598928.jpeg"))); // NOI18N
        bg.add(lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 0, 170, 130));

        lblDatos.setFont(new java.awt.Font("Coolvetica Rg", 1, 18)); // NOI18N
        lblDatos.setForeground(new java.awt.Color(0, 0, 0));
        lblDatos.setText("Ingrese sus datos!");
        bg.add(lblDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 200, 30));

        jLabel2.setFont(new java.awt.Font("Coolvetica Rg", 2, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Rut");
        bg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 40, 30));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Coolvetica Rg", 2, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nombre");
        bg.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 100, 40));

        jLabel4.setFont(new java.awt.Font("Coolvetica Rg", 2, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Apellido");
        bg.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 80, -1));

        jLabel5.setFont(new java.awt.Font("Coolvetica Rg", 2, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Edad");
        bg.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 70, 30));

        jLabel1.setFont(new java.awt.Font("Coolvetica Rg", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Plantasia");
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 40, 150, 30));

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        exitBtn.setBackground(new java.awt.Color(255, 255, 255));

        txtX.setFont(new java.awt.Font("Coolvetica Rg", 2, 24)); // NOI18N
        txtX.setForeground(new java.awt.Color(0, 0, 0));
        txtX.setText("X");
        txtX.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtX.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        txtX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtXMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtXMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtXMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitBtnLayout = new javax.swing.GroupLayout(exitBtn);
        exitBtn.setLayout(exitBtnLayout);
        exitBtnLayout.setHorizontalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtX, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        exitBtnLayout.setVerticalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 904, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bg.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 30));

        txtRut.setBackground(new java.awt.Color(255, 255, 255));
        txtRut.setFont(new java.awt.Font("Coolvetica Rg", 1, 14)); // NOI18N
        txtRut.setForeground(new java.awt.Color(204, 204, 204));
        txtRut.setText("Ingrese su rut...");
        txtRut.setBorder(null);
        txtRut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtRutMousePressed(evt);
            }
        });
        bg.add(txtRut, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 150, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 180, 10));

        txtNombre.setBackground(new java.awt.Color(255, 255, 255));
        txtNombre.setFont(new java.awt.Font("Coolvetica Rg", 1, 14)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(204, 204, 204));
        txtNombre.setText("Ingrese su nombre...");
        txtNombre.setBorder(null);
        txtNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNombreMousePressed(evt);
            }
        });
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        bg.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 150, -1));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 180, 10));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 180, 30));

        txtApellido.setBackground(new java.awt.Color(255, 255, 255));
        txtApellido.setFont(new java.awt.Font("Coolvetica Rg", 1, 14)); // NOI18N
        txtApellido.setForeground(new java.awt.Color(204, 204, 204));
        txtApellido.setText("Ingrese su apellido...");
        txtApellido.setBorder(null);
        txtApellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtApellidoMousePressed(evt);
            }
        });
        txtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoActionPerformed(evt);
            }
        });
        bg.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 150, -1));

        txtEdad.setBackground(new java.awt.Color(255, 255, 255));
        txtEdad.setFont(new java.awt.Font("Coolvetica Rg", 1, 14)); // NOI18N
        txtEdad.setForeground(new java.awt.Color(204, 204, 204));
        txtEdad.setText("Ingrese su edad...");
        txtEdad.setBorder(null);
        txtEdad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtEdadMousePressed(evt);
            }
        });
        txtEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdadActionPerformed(evt);
            }
        });
        bg.add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 140, -1));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 180, 20));

        lblDireccion.setFont(new java.awt.Font("Coolvetica Rg", 1, 18)); // NOI18N
        lblDireccion.setForeground(new java.awt.Color(0, 0, 0));
        lblDireccion.setText("Direccion");
        bg.add(lblDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 90, 40));

        lblCalle.setFont(new java.awt.Font("Coolvetica Rg", 0, 18)); // NOI18N
        lblCalle.setForeground(new java.awt.Color(0, 0, 0));
        lblCalle.setText("Calle");
        bg.add(lblCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, -1, -1));

        txtCalle.setBackground(new java.awt.Color(255, 255, 255));
        txtCalle.setFont(new java.awt.Font("Coolvetica Rg", 1, 14)); // NOI18N
        txtCalle.setForeground(new java.awt.Color(204, 204, 204));
        txtCalle.setText("Ingrese su calle...");
        txtCalle.setBorder(null);
        txtCalle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCalleMousePressed(evt);
            }
        });
        bg.add(txtCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 110, 20));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 200, 10));

        jLabel6.setFont(new java.awt.Font("Coolvetica Rg", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Comuna");
        bg.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 80, -1));

        txtComuna.setBackground(new java.awt.Color(255, 255, 255));
        txtComuna.setFont(new java.awt.Font("Coolvetica Rg", 1, 14)); // NOI18N
        txtComuna.setForeground(new java.awt.Color(204, 204, 204));
        txtComuna.setText("Ingrese su comuna...");
        txtComuna.setBorder(null);
        txtComuna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtComunaMousePressed(evt);
            }
        });
        bg.add(txtComuna, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, -1, 20));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 200, 10));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Coolvetica Rg", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("numero");
        bg.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, -1, -1));

        txtNumero.setBackground(new java.awt.Color(255, 255, 255));
        txtNumero.setFont(new java.awt.Font("Coolvetica Rg", 1, 14)); // NOI18N
        txtNumero.setForeground(new java.awt.Color(204, 204, 204));
        txtNumero.setText("Ingrese su numero...");
        txtNumero.setBorder(null);
        txtNumero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNumeroMousePressed(evt);
            }
        });
        txtNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroActionPerformed(evt);
            }
        });
        bg.add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, -1, -1));

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 200, 10));

        btnGuardar.setBackground(new java.awt.Color(0, 204, 153));
        btnGuardar.setFont(new java.awt.Font("Coolvetica Rg", 0, 18)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(0, 0, 0));
        btnGuardar.setText("Guardar");
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGuardarMouseExited(evt);
            }
        });
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        bg.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 120, 40));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Coolvetica Rg", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Planta");
        bg.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, 60, 20));

        txtPlanta.setBackground(new java.awt.Color(255, 255, 255));
        txtPlanta.setFont(new java.awt.Font("Coolvetica Rg", 1, 14)); // NOI18N
        txtPlanta.setForeground(new java.awt.Color(204, 204, 204));
        txtPlanta.setText("Ingrese su planta...");
        txtPlanta.setBorder(null);
        txtPlanta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtPlantaMousePressed(evt);
            }
        });
        bg.add(txtPlanta, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 160, -1, -1));

        jSeparator8.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 170, 10));

        jLabel10.setFont(new java.awt.Font("Coolvetica Rg", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Precio");
        bg.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, 70, -1));

        txtPrecio.setBackground(new java.awt.Color(255, 255, 255));
        txtPrecio.setFont(new java.awt.Font("Coolvetica Rg", 1, 14)); // NOI18N
        txtPrecio.setForeground(new java.awt.Color(204, 204, 204));
        txtPrecio.setText("Ingrese el precio...");
        txtPrecio.setBorder(null);
        txtPrecio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtPrecioMousePressed(evt);
            }
        });
        bg.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, -1, 20));

        jSeparator9.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 170, 10));

        tblPersona.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Rut", "Nombre", "Apellido", "Edad", "Calle", "Comuna", "Numero", "Planta", "Precio", "N°Seguimiento"
            }
        ));
        scrPersona.setViewportView(tblPersona);

        bg.add(scrPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, 570, 90));

        btnListar.setBackground(new java.awt.Color(0, 204, 153));
        btnListar.setFont(new java.awt.Font("Coolvetica Rg", 0, 18)); // NOI18N
        btnListar.setForeground(new java.awt.Color(0, 0, 0));
        btnListar.setText("Listar");
        btnListar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnListar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnListarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnListarMouseExited(evt);
            }
        });
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });
        bg.add(btnListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 390, 130, 40));

        btnMostrar.setBackground(new java.awt.Color(0, 204, 153));
        btnMostrar.setFont(new java.awt.Font("Coolvetica Rg", 0, 18)); // NOI18N
        btnMostrar.setForeground(new java.awt.Color(0, 0, 0));
        btnMostrar.setText("Mostrar");
        btnMostrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMostrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMostrarMouseExited(evt);
            }
        });
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });
        bg.add(btnMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 120, 40));

        btnAñadir.setBackground(new java.awt.Color(0, 204, 153));
        btnAñadir.setFont(new java.awt.Font("Coolvetica Rg", 0, 18)); // NOI18N
        btnAñadir.setForeground(new java.awt.Color(0, 0, 0));
        btnAñadir.setText("añadir");
        btnAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirActionPerformed(evt);
            }
        });
        bg.add(btnAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, 120, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 1010, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
       xMouse = evt.getX();
       yMouse = evt.getY();
       
    }//GEN-LAST:event_headerMousePressed

    private void txtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroActionPerformed
//metodo para el cierre de la app. Definiendo el boton X 
    private void txtXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtXMouseClicked
        System.exit(0);
    }//GEN-LAST:event_txtXMouseClicked
    //metodo para el arrastre de la barra superior 
    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void txtXMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtXMouseEntered
       exitBtn.setBackground(Color.red);
       txtX.setForeground(Color.white);
    }//GEN-LAST:event_txtXMouseEntered

    private void txtXMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtXMouseExited
       exitBtn.setBackground(Color.white);
       txtX.setForeground(Color.black);
    }//GEN-LAST:event_txtXMouseExited

    private void btnGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseEntered
       btnGuardar.setBackground(new Color(0,166,147));
    }//GEN-LAST:event_btnGuardarMouseEntered

    private void btnGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseExited
       btnGuardar.setBackground(new Color(0,204,153));
    }//GEN-LAST:event_btnGuardarMouseExited

    private void txtRutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRutMousePressed
       //metodo para borrar los textos gris, y darle otro enfoque uwu
       //a cada texto lo separamos con if, para que se pueda escribir de color negro, y que cuando queramos escribir en los otros espacios, no se borre nada
       if(txtRut.getText().equals("Ingrese su rut...")){
           txtRut.setText("");
           txtRut.setForeground(Color.black);
       }
       if(String.valueOf(txtNombre.getText()).isEmpty()){
           txtNombre.setText("Ingrese su nombre...");
           txtNombre.setForeground(Color.gray);
       }
       if(String.valueOf(txtApellido.getText()).isEmpty()){
           txtApellido.setText("Ingrese su apellido...");
           txtApellido.setForeground(Color.gray);
       }
       if(String.valueOf(txtEdad.getText()).isEmpty()){
           txtEdad.setText("Ingrese su edad...");
           txtEdad.setForeground(Color.gray);
       }
       if(String.valueOf(txtCalle.getText()).isEmpty()){
           txtCalle.setText("Ingrese su calle...");
           txtCalle.setForeground(Color.gray);
       }
       if(String.valueOf(txtComuna.getText()).isEmpty()){
           txtComuna.setText("Ingrese su comuna...");
           txtComuna.setForeground(Color.gray);
       }
       if(String.valueOf(txtNumero.getText()).isEmpty()){
           txtNumero.setText("Ingrese su numero...");
           txtNumero.setForeground(Color.gray);
       }
       if(String.valueOf(txtPlanta.getText()).isEmpty()){
           txtPlanta.setText("Ingrese su planta...");
           txtPlanta.setForeground(Color.gray);
       }
       if(String.valueOf(txtPrecio.getText()).isEmpty()){
           txtPrecio.setText("Ingrese el precio...");
           txtPrecio.setForeground(Color.gray);
       }
    }//GEN-LAST:event_txtRutMousePressed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
       
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
       
    }//GEN-LAST:event_txtApellidoActionPerformed

    private void txtEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdadActionPerformed
        
    }//GEN-LAST:event_txtEdadActionPerformed

    private void txtNombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreMousePressed
         //metodo para borrar los textos gris, y darle otro enfoque uwu
       //a cada texto lo separamos con if, para que se pueda escribir de color negro, y que cuando queramos escribir en los otros espacios, no se borre nada
       if(txtNombre.getText().equals("Ingrese su nombre...")){
           txtNombre.setText("");
           txtNombre.setForeground(Color.black);
       }
       if(String.valueOf(txtRut.getText()).isEmpty()){
           txtRut.setText("Ingrese su rut...");
           txtRut.setForeground(Color.gray);
       }
       if(String.valueOf(txtApellido.getText()).isEmpty()){
           txtApellido.setText("Ingrese su apellido...");
           txtApellido.setForeground(Color.gray);
       }
       if(String.valueOf(txtEdad.getText()).isEmpty()){
           txtEdad.setText("Ingrese su edad...");
           txtEdad.setForeground(Color.gray);
       }
       if(String.valueOf(txtCalle.getText()).isEmpty()){
           txtCalle.setText("Ingrese su calle...");
           txtCalle.setForeground(Color.gray);
       }
       if(String.valueOf(txtComuna.getText()).isEmpty()){
           txtComuna.setText("Ingrese su comuna...");
           txtComuna.setForeground(Color.gray);
       }
       if(String.valueOf(txtNumero.getText()).isEmpty()){
           txtNumero.setText("Ingrese su numero...");
           txtNumero.setForeground(Color.gray);
       }
       if(String.valueOf(txtPlanta.getText()).isEmpty()){
           txtPlanta.setText("Ingrese su planta...");
           txtPlanta.setForeground(Color.gray);
       }
       if(String.valueOf(txtPrecio.getText()).isEmpty()){
           txtPrecio.setText("Ingrese el precio...");
           txtPrecio.setForeground(Color.gray);
       }
    }//GEN-LAST:event_txtNombreMousePressed

    private void txtApellidoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtApellidoMousePressed
         //metodo para borrar los textos gris, y darle otro enfoque uwu
       //a cada texto lo separamos con if, para que se pueda escribir de color negro, y que cuando queramos escribir en los otros espacios, no se borre nada
       if(txtApellido.getText().equals("Ingrese su apellido...")){
           txtApellido.setText("");
           txtApellido.setForeground(Color.black);
       }
       if(String.valueOf(txtNombre.getText()).isEmpty()){
           txtNombre.setText("Ingrese su nombre...");
           txtNombre.setForeground(Color.gray);
       }
       if(String.valueOf(txtRut.getText()).isEmpty()){
           txtRut.setText("Ingrese su rut...");
           txtRut.setForeground(Color.gray);
       }
       if(String.valueOf(txtEdad.getText()).isEmpty()){
           txtEdad.setText("Ingrese su edad...");
           txtEdad.setForeground(Color.gray);
       }
       if(String.valueOf(txtCalle.getText()).isEmpty()){
           txtCalle.setText("Ingrese su calle...");
           txtCalle.setForeground(Color.gray);
       }
       if(String.valueOf(txtComuna.getText()).isEmpty()){
           txtComuna.setText("Ingrese su comuna...");
           txtComuna.setForeground(Color.gray);
       }
       if(String.valueOf(txtNumero.getText()).isEmpty()){
           txtNumero.setText("Ingrese su numero...");
           txtNumero.setForeground(Color.gray);
       }
       if(String.valueOf(txtPlanta.getText()).isEmpty()){
           txtPlanta.setText("Ingrese su planta...");
           txtPlanta.setForeground(Color.gray);
       }
       if(String.valueOf(txtPrecio.getText()).isEmpty()){
           txtPrecio.setText("Ingrese el  precio...");
           txtPrecio.setForeground(Color.gray);
       }
    }//GEN-LAST:event_txtApellidoMousePressed

    private void txtEdadMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEdadMousePressed
         //metodo para borrar los textos gris, y darle otro enfoque uwu
       //a cada texto lo separamos con if, para que se pueda escribir de color negro, y que cuando queramos escribir en los otros espacios, no se borre nada
       if(txtEdad.getText().equals("Ingrese su edad...")){
           txtEdad.setText("");
           txtEdad.setForeground(Color.black);
       }
       if(String.valueOf(txtNombre.getText()).isEmpty()){
           txtNombre.setText("Ingrese su nombre...");
           txtNombre.setForeground(Color.gray);
       }
       if(String.valueOf(txtRut.getText()).isEmpty()){
           txtRut.setText("Ingrese su rut...");
           txtRut.setForeground(Color.gray);
       }
       if(String.valueOf(txtApellido.getText()).isEmpty()){
           txtApellido.setText("Ingrese su apellido...");
           txtApellido.setForeground(Color.gray);
       }
       if(String.valueOf(txtCalle.getText()).isEmpty()){
           txtCalle.setText("Ingrese su calle...");
           txtCalle.setForeground(Color.gray);
       }
       if(String.valueOf(txtComuna.getText()).isEmpty()){
           txtComuna.setText("Ingrese su comuna...");
           txtComuna.setForeground(Color.gray);
       }
       if(String.valueOf(txtNumero.getText()).isEmpty()){
           txtNumero.setText("Ingrese su numero...");
           txtNumero.setForeground(Color.gray);
       }
       if(String.valueOf(txtPlanta.getText()).isEmpty()){
           txtPlanta.setText("Ingrese su planta...");
           txtPlanta.setForeground(Color.gray);
       }
       if(String.valueOf(txtPrecio.getText()).isEmpty()){
           txtPrecio.setText("Ingrese el precio...");
           txtPrecio.setForeground(Color.gray);
       }
    }//GEN-LAST:event_txtEdadMousePressed

    private void txtCalleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCalleMousePressed
         //metodo para borrar los textos gris, y darle otro enfoque uwu
       //a cada texto lo separamos con if, para que se pueda escribir de color negro, y que cuando queramos escribir en los otros espacios, no se borre nada
       if(txtCalle.getText().equals("Ingrese su calle...")){
           txtCalle.setText("");
           txtCalle.setForeground(Color.black);
       }
       if(String.valueOf(txtNombre.getText()).isEmpty()){
           txtNombre.setText("Ingrese su nombre...");
           txtNombre.setForeground(Color.gray);
       }
       if(String.valueOf(txtRut.getText()).isEmpty()){
           txtRut.setText("Ingrese su rut...");
           txtRut.setForeground(Color.gray);
       }
       if(String.valueOf(txtEdad.getText()).isEmpty()){
           txtEdad.setText("Ingrese su edad...");
           txtEdad.setForeground(Color.gray);
       }
       if(String.valueOf(txtApellido.getText()).isEmpty()){
           txtApellido.setText("Ingrese su calle...");
           txtApellido.setForeground(Color.gray);
       }
       if(String.valueOf(txtComuna.getText()).isEmpty()){
           txtComuna.setText("Ingrese su comuna...");
           txtComuna.setForeground(Color.gray);
       }
       if(String.valueOf(txtNumero.getText()).isEmpty()){
           txtNumero.setText("Ingrese su numero...");
           txtNumero.setForeground(Color.gray);
       }
       if(String.valueOf(txtPlanta.getText()).isEmpty()){
           txtPlanta.setText("Ingrese su planta...");
           txtPlanta.setForeground(Color.gray);
       }
       if(String.valueOf(txtPrecio.getText()).isEmpty()){
           txtPrecio.setText("Ingrese el precio...");
           txtPrecio.setForeground(Color.gray);
       }
    }//GEN-LAST:event_txtCalleMousePressed

    private void txtComunaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtComunaMousePressed
          //metodo para borrar los textos gris, y darle otro enfoque uwu
       //a cada texto lo separamos con if, para que se pueda escribir de color negro, y que cuando queramos escribir en los otros espacios, no se borre nada
       if(txtComuna.getText().equals("Ingrese su comuna...")){
           txtComuna.setText("");
           txtComuna.setForeground(Color.black);
       }
       if(String.valueOf(txtNombre.getText()).isEmpty()){
           txtNombre.setText("Ingrese su nombre...");
           txtNombre.setForeground(Color.gray);
       }
       if(String.valueOf(txtRut.getText()).isEmpty()){
           txtRut.setText("Ingrese su rut...");
           txtRut.setForeground(Color.gray);
       }
       if(String.valueOf(txtEdad.getText()).isEmpty()){
           txtEdad.setText("Ingrese su edad...");
           txtEdad.setForeground(Color.gray);
       }
       if(String.valueOf(txtApellido.getText()).isEmpty()){
           txtApellido.setText("Ingrese su apellido...");
           txtApellido.setForeground(Color.gray);
       }
       if(String.valueOf(txtCalle.getText()).isEmpty()){
           txtCalle.setText("Ingrese su calle...");
           txtCalle.setForeground(Color.gray);
       }
       if(String.valueOf(txtNumero.getText()).isEmpty()){
           txtNumero.setText("Ingrese su numero...");
           txtNumero.setForeground(Color.gray);
       }
       if(String.valueOf(txtPlanta.getText()).isEmpty()){
           txtPlanta.setText("Ingrese su planta...");
           txtPlanta.setForeground(Color.gray);
       }
       if(String.valueOf(txtPrecio.getText()).isEmpty()){
           txtPrecio.setText("Ingrese el precio...");
           txtPrecio.setForeground(Color.gray);
       }
    }//GEN-LAST:event_txtComunaMousePressed

    private void txtNumeroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNumeroMousePressed
  //metodo para borrar los textos gris, y darle otro enfoque uwu
       //a cada texto lo separamos con if, para que se pueda escribir de color negro, y que cuando queramos escribir en los otros espacios, no se borre nada
       if(txtNumero.getText().equals("Ingrese su numero...")){
           txtNumero.setText("");
           txtNumero.setForeground(Color.black);
       }
       if(String.valueOf(txtNombre.getText()).isEmpty()){
           txtNombre.setText("Ingrese su nombre...");
           txtNombre.setForeground(Color.gray);
       }
       if(String.valueOf(txtRut.getText()).isEmpty()){
           txtRut.setText("Ingrese su rut...");
           txtRut.setForeground(Color.gray);
       }
       if(String.valueOf(txtEdad.getText()).isEmpty()){
           txtEdad.setText("Ingrese su edad...");
           txtEdad.setForeground(Color.gray);
       }
       if(String.valueOf(txtApellido.getText()).isEmpty()){
           txtApellido.setText("Ingrese su calle...");
           txtApellido.setForeground(Color.gray);
       }
       if(String.valueOf(txtCalle.getText()).isEmpty()){
           txtCalle.setText("Ingrese su calle...");
           txtCalle.setForeground(Color.gray);
       }
       if(String.valueOf(txtComuna.getText()).isEmpty()){
           txtComuna.setText("Ingrese su comuna...");
           txtComuna.setForeground(Color.gray);
       }
       if(String.valueOf(txtPlanta.getText()).isEmpty()){
           txtPlanta.setText("Ingrese su planta...");
           txtPlanta.setForeground(Color.gray);
       }
       if(String.valueOf(txtPrecio.getText()).isEmpty()){
           txtPrecio.setText("Ingrese el precio...");
           txtPrecio.setForeground(Color.gray);
       }    }//GEN-LAST:event_txtNumeroMousePressed

    private void txtPlantaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPlantaMousePressed
         //metodo para borrar los textos gris, y darle otro enfoque uwu
       //a cada texto lo separamos con if, para que se pueda escribir de color negro, y que cuando queramos escribir en los otros espacios, no se borre nada
       if(txtPlanta.getText().equals("Ingrese su planta...")){
           txtPlanta.setText("");
           txtPlanta.setForeground(Color.black);
       }
       if(String.valueOf(txtNombre.getText()).isEmpty()){
           txtNombre.setText("Ingrese su nombre...");
           txtNombre.setForeground(Color.gray);
       }
       if(String.valueOf(txtRut.getText()).isEmpty()){
           txtRut.setText("Ingrese su rut...");
           txtRut.setForeground(Color.gray);
       }
       if(String.valueOf(txtEdad.getText()).isEmpty()){
           txtEdad.setText("Ingrese su edad...");
           txtEdad.setForeground(Color.gray);
       }
       if(String.valueOf(txtApellido.getText()).isEmpty()){
           txtApellido.setText("Ingrese su calle...");
           txtApellido.setForeground(Color.gray);
       }
       if(String.valueOf(txtComuna.getText()).isEmpty()){
           txtComuna.setText("Ingrese su comuna...");
           txtComuna.setForeground(Color.gray);
       }
       if(String.valueOf(txtNumero.getText()).isEmpty()){
           txtNumero.setText("Ingrese su numero...");
           txtNumero.setForeground(Color.gray);
       }
       if(String.valueOf(txtCalle.getText()).isEmpty()){
           txtCalle.setText("Ingrese su calle...");
           txtCalle.setForeground(Color.gray);
       }
       if(String.valueOf(txtPrecio.getText()).isEmpty()){
           txtPrecio.setText("Ingrese el precio...");
           txtPrecio.setForeground(Color.gray);
       }
    }//GEN-LAST:event_txtPlantaMousePressed

    private void txtPrecioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPrecioMousePressed
         //metodo para borrar los textos gris, y darle otro enfoque uwu
       //a cada texto lo separamos con if, para que se pueda escribir de color negro, y que cuando queramos escribir en los otros espacios, no se borre nada
       if(txtPrecio.getText().equals("Ingrese el precio...")){
           txtPrecio.setText("");
           txtPrecio.setForeground(Color.black);
       }
       if(String.valueOf(txtNombre.getText()).isEmpty()){
           txtNombre.setText("Ingrese su nombre...");
           txtNombre.setForeground(Color.gray);
       }
       if(String.valueOf(txtRut.getText()).isEmpty()){
           txtRut.setText("Ingrese su rut...");
           txtRut.setForeground(Color.gray);
       }
       if(String.valueOf(txtEdad.getText()).isEmpty()){
           txtEdad.setText("Ingrese su edad...");
           txtEdad.setForeground(Color.gray);
       }
       if(String.valueOf(txtApellido.getText()).isEmpty()){
           txtApellido.setText("Ingrese su calle...");
           txtApellido.setForeground(Color.gray);
       }
       if(String.valueOf(txtComuna.getText()).isEmpty()){
           txtComuna.setText("Ingrese su comuna...");
           txtComuna.setForeground(Color.gray);
       }
       if(String.valueOf(txtNumero.getText()).isEmpty()){
           txtNumero.setText("Ingrese su numero...");
           txtNumero.setForeground(Color.gray);
       }
       if(String.valueOf(txtPlanta.getText()).isEmpty()){
           txtPlanta.setText("Ingrese su planta...");
           txtPlanta.setForeground(Color.gray);
       }
       if(String.valueOf(txtCalle.getText()).isEmpty()){
           txtCalle.setText("Ingrese su calle...");
           txtCalle.setForeground(Color.gray);
       }
    }//GEN-LAST:event_txtPrecioMousePressed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String rut = txtRut.getText();
        String nombre = txtNombre.getText();
        String apellido = txtApellido.getText();
        int edad = 0;
        try {
            edad = Integer.parseInt(txtEdad.getText());
        }catch (Exception e){
            System.out.println("Solo se permiten numeros...");
            return;
        }
        String calle = txtCalle.getText();
        String comuna = txtComuna.getText();
        int numero = 0;
        try{
            numero = Integer.parseInt(txtNumero.getText());
        }catch (Exception e){
            System.out.println("Solo se permiten numeros");
            return;
        }
        String nombrePlanta = txtPlanta.getText();
        int precio = 0;
        try{
            precio = Integer.parseInt(txtPrecio.getText());
        }catch (Exception e){
            System.out.println("Solo se permiten numeros..");
            return;
        }
        int seguimiento = (int) nSeguimiento();
        
        
        //crear direccion
        Direccion direccion = new Direccion(calle, comuna, numero);
        //crear planta
        Planta planta = new Planta(nombrePlanta, precio, seguimiento);
        //crear persona
        Persona persona = new Persona(rut, nombre, apellido, edad, direccion, planta);
        
        
      
        
        this.gestionPersona.agregarPersona(persona);
        
        
        
        scrPersona.revalidate();
        scrPersona.repaint();
        tblPersona.revalidate();
        tblPersona.repaint();
       // if(gestionPersona.tamanioLIsta() > 0){
           // btnGuardar.setVisible(false);
        //}
        
       
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnListarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListarMouseEntered
        btnListar.setBackground(new Color(0,166,147));
    }//GEN-LAST:event_btnListarMouseEntered

    private void btnListarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListarMouseExited
        btnListar.setBackground(new Color(0,204,153));
    }//GEN-LAST:event_btnListarMouseExited

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        

        //asignamos los atributos a la posicion de la tabla. en caso de dejar espacios de sobra, .trim los suprimirá 
        o[0] = txtRut.getText().trim(); 
        o[1] = txtNombre.getText().trim(); 
        o[2] = txtApellido.getText().trim(); 
        o[3] = txtEdad.getText().trim(); 
        o[4] = txtCalle.getText().trim(); 
        o[5] = txtComuna.getText().trim(); 
        o[6] = txtNumero.getText().trim(); 
        o[7] = txtPlanta.getText().trim(); 
        o[8] = txtPrecio.getText().trim();
        o[9] = nSeguimiento();
        //lo agregamos a la tabla
        dtm.addRow(o);
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
        javax.swing.JOptionPane.showMessageDialog(this, 
                "Datos de persona : \n" +
                "\nRut: " + txtRut.getText() + 
                "\nNombre: " + txtNombre.getText() + 
                "\nApellido: " + txtApellido.getText() + 
                "\nEdad: " + txtEdad.getText() + 
                "\nCalle: " + txtCalle.getText() +
                "\nComuna: " + txtComuna.getText() +
                "\n Numero: " + txtNumero.getText() +
                "\nPlanta: " + txtPlanta.getText()  + 
                "\nPrecio: " + txtPrecio.getText() +
                "\n N°Seguimiento: " + nSeguimiento(),
                "Guardado",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnGuardarMouseClicked

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
       //definimos la clase tabla, para interponerlo en la clase sistema xd, y se abra el nuevo jframe
       Tabla tabla = new Tabla();
       tabla.setVisible(true);
       this.dispose();
       //definir las dimensiones
       tabla.setSize(900, 420);
       
       //posicion
       tabla.setLocation(450, 450);
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnMostrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarMouseEntered
        btnMostrar.setBackground(new Color(0,166,147));
    }//GEN-LAST:event_btnMostrarMouseEntered

    private void btnMostrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarMouseExited
        btnMostrar.setBackground(new Color(0,204,153));
    }//GEN-LAST:event_btnMostrarMouseExited

    private void btnAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirActionPerformed
        for (int i = 0; i < tblPersona.getRowCount(); i++) {
            String Datos[] = new String[10];
            Datos[0]= tblPersona.getValueAt(i,0).toString();
            Datos[1]= tblPersona.getValueAt(i,1).toString();
            Datos[2]= tblPersona.getValueAt(i,2).toString();
            Datos[3]= tblPersona.getValueAt(i,3).toString();
            Datos[4]= tblPersona.getValueAt(i,4).toString();
            Datos[5]= tblPersona.getValueAt(i,5).toString();
            Datos[6]= tblPersona.getValueAt(i,6).toString();
            Datos[7]= tblPersona.getValueAt(i,7).toString();
            Datos[8]= tblPersona.getValueAt(i,8).toString();
            Datos[9]= tblPersona.getValueAt(i,9).toString();
            
            Tabla.tabla2.addRow
}
            
                
    }//GEN-LAST:event_btnAñadirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnAñadir;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JPanel exitBtn;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lbl;
    private javax.swing.JLabel lblCalle;
    private javax.swing.JLabel lblDatos;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JScrollPane scrPersona;
    private javax.swing.JTable tblPersona;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCalle;
    private javax.swing.JTextField txtComuna;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtPlanta;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtRut;
    private javax.swing.JLabel txtX;
    // End of variables declaration//GEN-END:variables
}
