
package view;

import controller.Direccion;
import controller.Persona;
import controller.Planta;
import java.util.Random;
import javax.swing.JOptionPane;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import model.Gestion;

/**
 *
 * @author anideu
 */
public class editar extends javax.swing.JDialog {
    private Gestion gestionPersona;
    /**
     * Creates new form editar
     */
    private Object[] o = new Object[10];
    public editar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        gestionPersona = new Gestion();
        tbnTabla.setVisible(false);
        scrTabla.setVisible(false);
    }
    Random random = new Random();
    public double  nSeguimiento(){
        int numero = random.nextInt(1000); //generar un numero aleatorio entre 0 y 9999
        return numero; 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        txtCalle = new javax.swing.JTextField();
        txtComuna = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        txtPlanta = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        planta = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtRut = new javax.swing.JTextField();
        scrTabla = new javax.swing.JScrollPane();
        tbnTabla = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Coolvetica Rg", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 60, 30));

        jLabel3.setFont(new java.awt.Font("Coolvetica Rg", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Apellido");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 60, 30));

        jLabel4.setFont(new java.awt.Font("Coolvetica Rg", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Edad");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 40, 30));

        jLabel5.setFont(new java.awt.Font("Coolvetica Rg", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Calle");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 40, 30));

        jLabel6.setFont(new java.awt.Font("Coolvetica Rg", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Comuna");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 70, 20));

        jLabel7.setFont(new java.awt.Font("Coolvetica Rg", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Numero");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 60, 20));

        jLabel8.setFont(new java.awt.Font("Coolvetica Rg", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Planta");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, -1, -1));

        jLabel9.setFont(new java.awt.Font("Coolvetica Rg", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Precio");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, -1, -1));

        txtNombre.setBackground(new java.awt.Color(255, 255, 255));
        txtNombre.setForeground(new java.awt.Color(204, 204, 204));
        txtNombre.setText("Ingrese su nombre...");
        txtNombre.setBorder(null);
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 140, 20));

        txtApellido.setBackground(new java.awt.Color(255, 255, 255));
        txtApellido.setForeground(new java.awt.Color(204, 204, 204));
        txtApellido.setText("Ingrese su apellido...");
        txtApellido.setBorder(null);
        jPanel1.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 140, 20));

        txtEdad.setBackground(new java.awt.Color(255, 255, 255));
        txtEdad.setForeground(new java.awt.Color(204, 204, 204));
        txtEdad.setText("Ingrese su edad...");
        txtEdad.setBorder(null);
        jPanel1.add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 120, -1));

        txtCalle.setBackground(new java.awt.Color(255, 255, 255));
        txtCalle.setForeground(new java.awt.Color(204, 204, 204));
        txtCalle.setText("Ingrese su calle...");
        txtCalle.setBorder(null);
        jPanel1.add(txtCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 140, -1));

        txtComuna.setBackground(new java.awt.Color(255, 255, 255));
        txtComuna.setForeground(new java.awt.Color(204, 204, 204));
        txtComuna.setText("Ingrese su comuna...");
        txtComuna.setBorder(null);
        txtComuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtComunaActionPerformed(evt);
            }
        });
        jPanel1.add(txtComuna, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 130, -1));

        txtNumero.setBackground(new java.awt.Color(255, 255, 255));
        txtNumero.setFont(new java.awt.Font("Coolvetica Rg", 0, 14)); // NOI18N
        txtNumero.setForeground(new java.awt.Color(204, 204, 204));
        txtNumero.setText("Ingrese su numero....");
        txtNumero.setBorder(null);
        jPanel1.add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, -1, -1));

        txtPlanta.setBackground(new java.awt.Color(255, 255, 255));
        txtPlanta.setForeground(new java.awt.Color(0, 0, 0));
        txtPlanta.setText("jTextField7");
        txtPlanta.setBorder(null);
        jPanel1.add(txtPlanta, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, -1, -1));

        txtPrecio.setBackground(new java.awt.Color(255, 255, 255));
        txtPrecio.setForeground(new java.awt.Color(0, 0, 0));
        txtPrecio.setText("jTextField8");
        txtPrecio.setBorder(null);
        jPanel1.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, -1, -1));

        planta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/planta.jpeg"))); // NOI18N
        jPanel1.add(planta, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 340, 480));

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 110, 40));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 100, 40));

        txtRut.setBackground(new java.awt.Color(255, 255, 255));
        txtRut.setFont(new java.awt.Font("Coolvetica Rg", 0, 14)); // NOI18N
        txtRut.setForeground(new java.awt.Color(204, 204, 204));
        txtRut.setText("Ingrese su rut....");
        txtRut.setBorder(null);
        txtRut.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(txtRut, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 120, -1));

        tbnTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "rut", "nombre", "apellido", "edad", "calle", "Title 6", "numero", "planta", "precio", "seguimiento"
            }
        ));
        scrTabla.setViewportView(tbnTabla);

        jPanel1.add(scrTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 370, 80, 50));

        jLabel10.setFont(new java.awt.Font("Nexa Heavy", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Rut");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 50, 30));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 130, 10));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 130, 10));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 130, 10));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 130, 10));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 130, 10));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 120, 10));

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 120, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void configurarTabla(){
        tbnTabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void moseClicked(java.awt.event.MouseEvent evt ){
                int filaSeleccionada = tbnTabla.getSelectedRow();
                if(filaSeleccionada >= 0){
                    //obtener los valores del objeto
                    String rut = (String) tbnTabla.getValueAt(filaSeleccionada, 0);
                    String nombre = (String) tbnTabla.getValueAt(filaSeleccionada, 1);
                    String apellido = (String) tbnTabla.getValueAt(filaSeleccionada, 2);
                    int edad = (int) tbnTabla.getValueAt(filaSeleccionada, 3);
                    String calle = (String) tbnTabla.getValueAt(filaSeleccionada, 4);
                    String comuna = (String) tbnTabla.getValueAt(filaSeleccionada, 5);
                    int numero = (int) tbnTabla.getValueAt(filaSeleccionada, 6);
                    String nombrePlanta = (String) tbnTabla.getValueAt(filaSeleccionada, 7);
                    int precio = (int) tbnTabla.getValueAt(filaSeleccionada, 8);
                    
                    txtRut.setText(rut);
                    txtNombre.setText(nombre);
                    txtApellido.setText(apellido);
                    txtEdad.setText(String.valueOf(edad));
                    txtCalle.setText(calle);
                    txtComuna.setText(comuna);
                    txtPlanta.setText(nombrePlanta);
                    txtPrecio.setText(String.valueOf(precio));
                    txtNumero.setText(String.valueOf(numero));
                    
                    //inhabilitar el campo rut
                    txtRut.setEnabled(false);
                }
                
            }
        });
    }
    
    
    
    
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        //marcar el JDialog como no accesible, o sea que fue marcado para destruccion
        this.setRootPane(null); //poner el rootPane del dialog sera null, haciendolo inservible
        this.dispose(); //destruye de la memoria el JDialog actual
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        
        int filaSeleccionada = tbnTabla.getSelectedRow();
        if(filaSeleccionada >= 0){
            String rut = txtRut.getText();
            String nombre = txtNombre.getText();
            String apellido = txtApellido.getText();
            String calle = txtCalle.getText();
            String comuna = txtComuna.getText();
            String nombrePlanta = txtPlanta.getText();
            String precio = txtPrecio.getText();
            int seguimiento =  (int) nSeguimiento();
            int edad = 0;
            try {
                edad = Integer.parseInt(txtEdad.getText());
            }catch (Exception e){
                JOptionPane.showMessageDialog(this,"el campo apellido no puede venir vacio!!");
                return;
            }
            int numero = 0;
            try {
                numero = Integer.parseInt(txtNumero.getText());
            }catch (Exception e){
                JOptionPane.showMessageDialog(this,"el campo numero no puede venir vacio!!");
                return;
            }
            int precios = 0;
            try {
                precios = Integer.parseInt(txtPrecio.getText());
            }catch (Exception e){
                JOptionPane.showMessageDialog(this,"el campo Precio no puede venir vacio!!");
                return;
            }
            Direccion direccionModificada = new Direccion(calle, comuna, numero);
            Planta plantaModificada = new Planta(nombrePlanta, precios, seguimiento);
            Persona personaModificada = new Persona(rut, nombre, apellido, edad, direccionModificada, plantaModificada);
            gestionPersona.modificarPersona(filaSeleccionada, personaModificada);
            
            //actualizar la tabla
            tbnTabla.setValueAt(rut, filaSeleccionada, 0);
            tbnTabla.setValueAt(nombre, filaSeleccionada, 1);
            tbnTabla.setValueAt(apellido, filaSeleccionada, 2);
            tbnTabla.setValueAt(edad, filaSeleccionada, 3);
            tbnTabla.setValueAt(calle, filaSeleccionada, 4);
            tbnTabla.setValueAt(comuna, filaSeleccionada, 5);
            tbnTabla.setValueAt(numero, filaSeleccionada, 6);
            tbnTabla.setValueAt(nombrePlanta, filaSeleccionada, 7);
            tbnTabla.setValueAt(precio, filaSeleccionada, 8);
            tbnTabla.setValueAt(seguimiento, filaSeleccionada, 9);
        }


        //boton aceptar, y validar los datos antes de enviarlos
        try{
            //ingresar el nombre del producto
            if(txtNombre.getText().trim().length() == 0){
               
                return;
            }
            if(txtApellido.getText().trim().length() == 0){
                JOptionPane.showMessageDialog(this,"el campo apellido no puede venir vacio!!");
                return;
            }
            if(txtCalle.getText().trim().length() == 0){
                JOptionPane.showMessageDialog(this, "el campo calle no puede venir vacio!!");
                return;
            }
            if(txtPlanta.getText().trim().length() == 0){
                JOptionPane.showMessageDialog(this, "el campo Planta no puede venir vacio!!");
                return;
            }
            if(txtComuna.getText().trim().length() == 0){
                JOptionPane.showMessageDialog(this, "el campo comuna no puede venir vacio!!");
                return;
            }
            this.setVisible(false);
            
        }catch (Exception e){
            JOptionPane.showMessageDialog(this,"los datos ingresados no son validos!");
            return;
        }
        
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void txtComunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtComunaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtComunaActionPerformed

    /**
     * @param args the command line aruments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                editar dialog = new editar(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel planta;
    private javax.swing.JScrollPane scrTabla;
    private javax.swing.JTable tbnTabla;
    public javax.swing.JTextField txtApellido;
    public javax.swing.JTextField txtCalle;
    public javax.swing.JTextField txtComuna;
    public javax.swing.JTextField txtEdad;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JTextField txtNumero;
    public javax.swing.JTextField txtPlanta;
    public javax.swing.JTextField txtPrecio;
    public javax.swing.JTextField txtRut;
    // End of variables declaration//GEN-END:variables
}
