package view;



import controller.Direccion;
import controller.Persona;
import controller.Planta;
import view.Sistema;
import javax.swing.table.DefaultTableModel;
import java.awt.Color;
import java.util.Random;
import java.util.Vector;
import javax.swing.JOptionPane;
import model.Gestion;


/**
 *
 * @author anideu
 */
public class Tabla extends javax.swing.JFrame {
    
        Planta planta;
        Direccion direccion;
        Persona persona;
        Gestion gestionPersona = new Gestion();
        public static DefaultTableModel modelo2;
        
    
        int xMouse, yMouse;
    /**
     * Creates new form Tabla
     */
    public Tabla() {
        initComponents();
        setLocationRelativeTo(this);
        //inicializa el modelo de la tabla
        modelo2 = new DefaultTableModel();
        
        modelo2.addColumn("Rut");
        modelo2.addColumn("Nombre");
        modelo2.addColumn("Apellido");
        modelo2.addColumn("Calle");
        modelo2.addColumn("Comuna");
        modelo2.addColumn("Numero");
        modelo2.addColumn("Planta");
        modelo2.addColumn("Precio");
        modelo2.addColumn("N°Seguimiento");
        tbnTabla2.setModel(modelo2);
       
         
    }
    
    Random random = new Random();
    public double  nSeguimiento(){
        int numero = random.nextInt(1000); //generar un numero aleatorio entre 0 y 9999
        return numero; 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbl = new javax.swing.JLabel();
        scrTabla = new javax.swing.JScrollPane();
        tbnTabla2 = new javax.swing.JTable();
        btnVolver = new javax.swing.JButton();
        header = new javax.swing.JPanel();
        btnExit = new javax.swing.JPanel();
        txtExit = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        content.setBackground(new java.awt.Color(255, 255, 255));
        content.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Coolvetica Rg", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Tabla");
        content.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/planta.jpeg"))); // NOI18N
        content.add(lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 0, 120, 420));

        tbnTabla2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Rut", "Nombre", "Apellido", "Edad", "Calle", "Comuna", "Numero", "Planta", "Precio", "N°Seguimiento"
            }
        ));
        scrTabla.setViewportView(tbnTabla2);

        content.add(scrTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 780, 200));

        btnVolver.setBackground(new java.awt.Color(0, 204, 153));
        btnVolver.setFont(new java.awt.Font("Coolvetica Rg", 0, 18)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(0, 0, 0));
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        content.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 130, 40));

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(255, 255, 255));

        txtExit.setFont(new java.awt.Font("Coolvetica Rg", 2, 24)); // NOI18N
        txtExit.setForeground(new java.awt.Color(0, 0, 0));
        txtExit.setText("X");
        txtExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtExitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnExitLayout = new javax.swing.GroupLayout(btnExit);
        btnExit.setLayout(btnExitLayout);
        btnExitLayout.setHorizontalGroup(
            btnExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnExitLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtExit, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        btnExitLayout.setVerticalGroup(
            btnExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnExitLayout.createSequentialGroup()
                .addComponent(txtExit, javax.swing.GroupLayout.PREFERRED_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 867, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        content.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 40));

        jLabel3.setFont(new java.awt.Font("Coolvetica Rg", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Plantasia");
        content.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 40, -1, -1));

        btnEliminar.setBackground(new java.awt.Color(0, 204, 153));
        btnEliminar.setFont(new java.awt.Font("Coolvetica Rg", 0, 18)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(0, 0, 0));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        content.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 130, 40));

        btnEditar.setBackground(new java.awt.Color(0, 204, 153));
        btnEditar.setFont(new java.awt.Font("Coolvetica Rg", 0, 18)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(0, 0, 0));
        btnEditar.setText("Modificar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        content.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 120, 40));

        btnAgregar.setBackground(new java.awt.Color(0, 204, 153));
        btnAgregar.setForeground(new java.awt.Color(0, 0, 0));
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        content.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, 120, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseEntered
        //metodo para coloreaar el boto nX cuando el mouse pase por encima de e l
        btnExit.setBackground(Color.red);
        txtExit.setForeground(Color.white);
    }//GEN-LAST:event_txtExitMouseEntered

    private void txtExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseExited
       btnExit.setBackground(Color.white);
       txtExit.setForeground(Color.black);
    }//GEN-LAST:event_txtExitMouseExited

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
      //eventos del mouse
      yMouse = evt.getY();
      xMouse = evt.getX();
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
       int x = evt.getXOnScreen();
       int y = evt.getYOnScreen();
       this.setLocation( x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        Sistema volver = new Sistema();
        volver.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void txtExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseClicked
       System.exit(0);
    }//GEN-LAST:event_txtExitMouseClicked

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
          
        //funcion que eliminar la fila seleccionada
        if (tbnTabla2.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(null, "no ha seleccionado un registro de la tabla..., ","ERROR AL ELIMINAR PERSONA", JOptionPane.ERROR_MESSAGE);
        
        }else {
            modelo2.removeRow(tbnTabla2.getSelectedRow());
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
       //boton para editar la fila seleccionada
       //primero validar que se ha seleccionado una fila
       if(tbnTabla2.getSelectedRow() == -1){
           return; //si no ha sido seleccionada una fila, se devuelve
       }
       
       
       
        //mostrar un JDialog de editar
        editar x = new editar(this, true);
        Vector registro;
        //recuperar e lvector almacenado en la fila seleccionada en el JTable
        registro = modelo2.getDataVector().elementAt(tbnTabla2.getSelectedRow());
       
        x.txtRut.setText(registro.elementAt(0).toString());
        x.txtNombre.setText(registro.elementAt(1).toString());
        x.txtApellido.setText(registro.elementAt(2).toString());
        x.txtEdad.setText(registro.elementAt(3).toString());
        x.txtCalle.setText(registro.elementAt(4).toString());
        x.txtComuna.setText(registro.elementAt(5).toString());
        x.txtNumero.setText(registro.elementAt(6).toString());
        x.txtPlanta.setText(registro.elementAt(7).toString());
        x.txtPrecio.setText(registro.elementAt(8).toString());
      
      
        x.setVisible(true);
        
        //si el rootPane del editar no es null, entonces se hizo click en aceptar
        if(x.getRootPane() != null ){
            //hizo click en Aceptar
            Vector v = new Vector();
            v.addElement(x.txtRut.getText());
            v.addElement(x.txtNombre.getText());
            v.addElement(x.txtApellido.getText());
            v.addElement(x.txtEdad.getText());
            v.addElement(x.txtCalle.getText());
            v.addElement(x.txtComuna.getText());
            v.addElement(x.txtNumero.getText());
            v.addElement(x.txtPlanta.getText());
            v.addElement(x.txtPrecio.getText());
            v.addElement(x.nSeguimiento());
            
            modelo2.getDataVector().set(tbnTabla2.getSelectedRow(), v);
            //Jace un resfresh a los graficos del JTable
            tbnTabla2.updateUI();
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        //mandar a llamar el JDialog de editar
        editar x = new editar(this, true);
        x.setVisible(true);

        //verificar si se click en ACEPTAR
        //si el rootPane del JDialog no es nulo entonces se hizo click en ACEPTAR
        if(x.getRootPane() != null){
            //agregar al grid los datos de JDialog llamado editar
            //crear un vector para la fila
            Vector v = new Vector();
            v.addElement (x.txtNombre.getText());
            v.addElement (x.txtApellido.getText());
            v.addElement (x.txtEdad.getText());
            v.addElement (x.txtCalle.getText());
            v.addElement (x.txtComuna.getText());
            v.addElement (x.txtNumero.getText());
            v.addElement (x.txtPlanta.getText());
            v.addElement (x.txtPrecio.getText());
            v.addElement (x.nSeguimiento());
            //agregar la fila  tabla
            modelo2.addRow(v);
        }

    }//GEN-LAST:event_btnAgregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tabla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JPanel btnExit;
    private javax.swing.JButton btnVolver;
    private javax.swing.JPanel content;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbl;
    private javax.swing.JScrollPane scrTabla;
    private javax.swing.JTable tbnTabla2;
    private javax.swing.JLabel txtExit;
    // End of variables declaration//GEN-END:variables
}
